### ISSUE TITLE
Possibilty to read appinfo.vdf

### ISSUE THREAD

**Issue by cyberpunkbln** [Corecii/steam_vdf#2]
Hello,

is it possible to read the the appinfo.vdf. When i try it with your doc-example i receive and empty/nonreadable error?

thx

**Comment by Corecii** [comment]
It doesn't look like `appinfo.vdf` follows the same format as `shortcuts.vdf`. VDF seems to be used not to tag files following a certain format, but instead to tag *any* internal files that are intended for only Valve to read.

For example, check out `localization.vdf` in the same directory. It's *definitely* not in the same format as `shortcuts.vdf`, since it's human-readable, where `shortcuts.vdf` is not.

If `appinfo.vdf` was the same format as `shortcuts.vdf`, then I would expect the first byte to be `0x00`, `0x01`, `0x02`, or `0x08`. On my file, the first byte is `0x27`, which is clearly not the same format unless it has been greatly expanded since this crate was written -- in which case, it's not supported anyway.
